### ISSUE TITLE
Cannot parse new XCTrack files

### ISSUE THREAD

**Issue by hyperknot** [Turbo87/igc-parser#29]
igc-parses terminates on new XCTrack files. The reason is the harmless 
```
HSCCLCOMPETITION CLASS:FAI-3
```
line present.

The error message is:
```
Error: Invalid GID header at line 6: HSCCLCOMPETITION CLASS:FAI-3
```

I'd be important not to terminating in case a harmless line like this one is present.

Sample IGC can be downloaded from here 
https://www.xcontest.org/world/en/flights/detail:zsero/26.6.2018/10:10

**Comment by Turbo87** [comment]
@hyperknot you can try out the `lenient` parsing mode that got introduced in https://github.com/Turbo87/igc-parser/pull/20

**Comment by hyperknot** [comment]
Thanks, this works with lenient. Still, might be a good idea to just allow all custom headers?

**Comment by Turbo87** [comment]
what I might do is make `lenient` the default, and use a `strict` option instead, since most users would probably want the `lenient` mode

**Comment by hyperknot** [comment]
Yes, I agree. I believe the XCTrack guys are usually following the official specs though.

**Comment by zevero** [comment]
I run into this as well. Please do the change and set lenient as the default!

**Comment by eltorio** [comment]
Hi I have the same problem the problem is due to XCTRACK competition class header
HSCCLCOMPETITION CLASS:FAI-3 (PG)
but the regex needs to be changed:
-var RE_CCL_HEADER = /^H[FO]CCL(?:.{0,}?:(.*)|(.*))$/;
+var RE_CCL_HEADER = /^H[FOS]CCL(?:.{0,}?:(.*)|(.*))$/;
because header is not HFCCL… nor HOCCL… but it is HSCCL…
Thanks for your work.
Ronan
