### ISSUE TITLE
Uncaught Error: Missing A record

### ISSUE THREAD

**Issue by hyperknot** [Turbo87/igc-parser#31]
Many IGC files from multiple instruments/software are throwing 
```
Uncaught Error: Missing A record
```
and failing parsing, even with lenient mode.

Example files:
https://www.xcontest.org/hungary/repulesek/reszletei:donath/26.06.2018/09:23
https://www.xcontest.org/hungary/repulesek/reszletei:lorta/26.06.2018/09:36

**Comment by Turbo87** [comment]
those flights are using
```
AXCT XCTrack 0.6.0 on samsung GT-S6500 2.3.6
```
which doesn't look like a valid A record to me

according to http://www.ukiws.demon.co.uk/GFAC/documents/tech_spec_gnss.pdf the "additional data" should start with a colon to separate it from the serial number.

you should open an issue with XCTrack so that they can fix their IGC output. I agree though that the error output could be improved for this case and the `lenient` mode should probably ignore this too.

**Comment by hyperknot** [comment]
1. For XCTrack, the new version already has good output, so they cannot fix the old versions backwards. 
2. For the second track / TTLiveTrack24, the record is `AXTT` yet it still throws this exception.

It'd be important to make this error into lenient mode instead of throwing an exception.

**Comment by hyperknot** [comment]
You are right, here is the official specs:

![image](https://user-images.githubusercontent.com/494223/42029710-be72d10e-7ad0-11e8-9c62-2d51161fd6b5.png)

**Comment by vicb** [comment]
According to the spec `AXCT XCTrack 0.6.0 on samsung GT-S6500 2.3.6` seems valid to me
*Non IGC FRs may use different system*
